---
# tasks file for consul-template

- name: Write install script
  template:
    src=install.j2
    dest={{consul_template_install_script}}
    mode=0755
  tags:
    - consul-template

- name: Check consul-template version
  shell: consul-template --version >> tmp.ver 2>&1 && cat tmp.ver  | grep {{consul_template_ver}}
  ignore_errors: true
  register: consul_template_ver_matches
  tags:
    - consul-template

- name: Install consul-template
  shell: "{{consul_template_install_script}}"
  when: consul_template_ver_matches|failed
  tags:
    - consul-template

- name: Verify binary
  shell: "stat {{consul_template_bin_path}}/{{consul_template_bin_name}}"
  tags:
    - consul-template

- name: Make templates dir
  file:
    path={{consul_template_templates_dir}}
    state=directory
  tags:
    - consul-template
